/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "${cognito_identitypool_id}",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "${cognito_userpool_id}",
    "aws_user_pools_web_client_id": "${cognito_client_id}",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "${storage_bucket}",
    "aws_user_files_s3_bucket_region": "ap-southeast-1",
    "aws_api_url": "${api_gw}/api/v1/identify"
};


export default awsmobile;
